apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bstm
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: bstm 
    spec:
      containers:
      - name: bstm 
        image: kdunetz/bstm:1.0 
        imagePullPolicy: Always 
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
